name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting with Go ${{ matrix.gov }} on ${{ matrix.os}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        gov: [1.23]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go ${{ matrix.gov }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.gov }}

      # Install required packages including git
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates git
          sudo update-ca-certificates

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
  
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m